archives:
  - files:
      - LICENSE
      - README.md
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
before:
  hooks:
    - go mod tidy
builds:
  - binary: '{{ .ProjectName }}-unsigned_{{ .Version }}'
    flags:
      - -trimpath
    goarch:
      - amd64
    goos:
      - freebsd
      - darwin
      - linux
      - windows
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - echo "{{ .Path }}"
        - echo "{{ .Dir }}"
    #hooks:
    #  post:
    #    - osslsigncode sign -h sha512 -certs "$SIGNING_CERT" -key "$SIGNING_KEY" -n "GSP - Git Simple Packager" -i "https://websbygeorge.com" -t "http://timestamp.comodoca.com/authenticode" -in {{ .Path }} -out {{ .Path }}/{{ .ProjectName }}_{{ .Version }}
changelog:
  skip: true
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
dist: build
env:
  - CGO_ENABLED=0
release:
  draft: true
